# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'honeycomb' do
    use_frameworks!

    # Pods for honeycomb


    target 'honeycombTests' do
        inherit! :search_paths
        # Pods for testing
    end
end
