# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'honeycomb' do
    use_frameworks!

    # Pods for honeycomb
    # Flexbox Layout Manager Used By React Natve
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
    
    # React Native
    pod 'React', path: '../node_modules/react-native', subspecs: [
    # Comment out any unneeded subspecs to reduce bundle size.
    'Core',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTCameraRoll',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTTest',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS',
    'BatchedBridge'
    ]
    
    # Mapbox
    pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'

    target 'honeycombTests' do
        inherit! :search_paths
        # Pods for testing
    end
end
